### ISSUE TITLE
Feature req: 'raw' or 'verbatim' blocks like Django

### ISSUE THREAD

**Issue by jackcarrozzo** [mmontone/djula#10]
Ran into a surprising problem where Angular tags in my page are getting interpreted as (empty) Djula tags, oops. Is there an easy way around that?

**Comment by mmontone** [comment]
I think there no verbatim currently implemented. I'see if I can implement something in the following days.

**Comment by mmontone** [comment]
Something like:

```
{% verbatim %}
    {{if dying}}Still alive.{{/if}}
{% endverbatim %}
```

would solve your problem?

**Comment by jackcarrozzo** [comment]
Yes, either a verbatim block that doesn't interpret ````{{ }}````, or a keyword arg to ````render```` to either disable replacing the double brackets or the ability to pass a different set of chars to use (ie ````{[{ }]}```` or similar).

I can dig into it a bit this week and send a PR, doesn't look like it'd be hard to do.

**Comment by mmontone** [comment]
I've looked a bit into this and it seems this has to be solved even before the tokenization pass. So, a {% verbatim %} tag cannot be implemented like the other tags as all the other tags work on an already tokenized body, unlike verbatim.

So, for a start, we could introduce something at the syntax level. I've implemented something very simple already: {$ this is {{verbatim}} $} syntax as i can demonstrate here:

```
(with-output-to-string (s)
	   (funcall (djula::compile-string "{$ this is {{verbatim}} $}") s))
=>
" this is {{verbatim}} "
```

Now, this may have a couple of problems. One, this is not Django templates syntax (I'm not sure there's a problem with that, though). Two, it may not work very well for a large verbatim body. A {{% verbatim %} tag would be better for that IMO.

**Comment by mmontone** [comment]
Please let me know what you think of it and if you want to have it like that.

**Comment by jackcarrozzo** [comment]
The ````{$ ... $}```` syntax would work for me certainly - though your second point would work equally well. I could honestly see myself using both of them, but would be perfectly fine with one or the other.

**Comment by mmontone** [comment]
Ok. I pushed a commit for the first syntax. Let me know if it is useful to you. I will add tests cases and document later if it is fine.

**Comment by jackcarrozzo** [comment]
Works great!! Thanks a bunch!
