### ISSUE TITLE
Tests take too long due to runtime compilation

### ISSUE THREAD

**Issue by PuercoPop** [mmontone/djula#19]
For example, in my machine (run 'filters) took ~10 seconds and crashed sbcl due to heap exhaustion if ran twice w/o calling gc.

Scymtm [pointed out](http://log.irc.tymoon.eu/freenode/lisp?around=2015-09-13T16:06:10&types=mnaot#1442160370) hat by default fiveam compiles tests at runtime. We should use `(def-test <name> (:compile-at :definition-time) ...)` instead. Although I'm unsure of the implications of that except for faster test times.

Is moving to prove an option?

**Comment by mmontone** [comment]
@PuercoPop Is this solved now?

**Comment by PuercoPop** [comment]
No, I just updated sbcl to the current head. Previously (asdf:test-system :djula) would crash sbcl due to heap exhaustion. I had to load each buffer separately and gc aftewards to avoid that. ccl has no problem. Could you check if this works ok on your machine? Am I the only one experiencing this issue?


```lisp
(require 'sb-cover)

(declaim (optimize sb-cover:store-coverage-data))
(asdf:oos 'asdf:load-op :djula :force t)
(asdf:oos 'asdf:load-op :djula-test)

(asdf:test-system :djula)

(sb-cover:report (asdf:system-relative-pathname :djula
                                                "report/"))
```

**Comment by mmontone** [comment]
I've never experienced this. Tests run fine on my Linux SBCL. Let me run your code to check...

**Comment by mmontone** [comment]
Your code runs very smoothly on my machine. It is a simple Linux laptop with SBCL:

```
marian@gimli ~ $ uname -a
Linux gimli 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
marian@gimli ~ $ sbcl --version
SBCL 1.2.11.39-077e40f
```

**Comment by PuercoPop** [comment]
In both "1.2.3.936-7c9c999" and "1.2.14.155-d31b733" I get. Weird

```
Heap exhausted during garbage collection: 0 bytes available, 32 requested.
 Gen StaPg UbSta LaSta LUbSt Boxed Unboxed LB   LUB  !move  Alloc  Waste   Trig    WP  GCs Mem-age
   0:     0     0     0     0     0     0     0     0     0        0     0 10737418    0   0  0,0000
   1: 27089 29711     0     0  2750  7410     0     0    14 322201136 10721744 10737418    0   0  0,9993
   2: 24065 24066     0     0  7202  2551     5    24    97 318987024 1549552 10737418 6205   0  0,1620
   3: 14062 14060     0     0  2812  1097    87   215   142 134876112 3109936  2000000 2058   0  0,0000
   4:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0,0000
   5:     0     0     0     0     0     0     0     0     0        0     0  2000000    0   0  0,0000
   6:     0     0     0     0  1700   235     0     0     0 63406080     0  2000000 1534   0  0,0000
   Total bytes allocated    = 1048056256
   Dynamic-space-size bytes = 1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 18951(tid 140737255470848):
Heap exhausted, game over.

Error opening /dev/tty: No such device or address
Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 
```

**Comment by mmontone** [comment]
This is hanging for me now, on render-template*

```
(let ((fn (djula::compile-string
             "{% ifequal day \"Thursday\" %}
I never could get the hang of {{ day }}s.
{% endifequal %}")
          ))
			  (djula::render-template* fn nil :day "Thursday"))
```

**Comment by mmontone** [comment]
Ok. See the error. There's a potential problem when some rendering error occurs, that makes djula:render-template* to be called recursively ad-infinity. So this is not a closed issue. Should be debugged.

**Comment by PuercoPop** [comment]
Related sbcl-help: 

http://sourceforge.net/p/sbcl/mailman/sbcl-help/thread/CAAmBhX9Q4UGQ8pMrTK6qOQC6dYg-ZfbDvXwrCUG5VrtcNJ_J7g%40mail.gmail.com/#msg34467846

**Comment by PuercoPop** [comment]
Would you consider 1am? The api is similar to 5am, but smaller. Conses a lot less but its reports are moe spartan.

This is unrelated to the render-template* above

**Comment by mmontone** [comment]
I could consider 1am, but I would like to know the reason there's a problem with 5am. Djula stuff should be pretty straightforward. If tests take too long, then there must be a problem in Djula implementation, and it should be removed.

**Comment by PuercoPop** [comment]
I'm sure there is a problem there is a problem in the Djula implementation in process-tokens. For example, [this is recursion from a not tail call position](https://github.com/mmontone/djula/blob/master/src/parser.lisp#L44). However, 5am code is [not the best either](https://github.com/sionescu/fiveam/blob/master/src/test.lisp#L121).

I have a decent workaround now, I can work by patching the branch I an working on and rebasing to remove the patch before submiting the PR.
