### ISSUE TITLE
Move pipeline functions out of property lists into packages

### ISSUE THREAD

**Issue by PuercoPop** [mmontone/djula#20]
To illustrate what I mean I wrote the code for filters. You can see the prelimary work here: https://github.com/PuercoPop/djula/tree/pipeline-packages

Btw, what is preferred, using dots or slashes (or just dashes) as package 'hierarchy' separators?

**Comment by mmontone** [comment]
Regarding package 'hierarchy' separators, I'm used to using dots. And Fukamachi uses them too.

But: A package like "djula.filters" shows in my SLIME repl as just "filters". So, maybe your "djula/filters" is better in that regard. Maybe it is time to try a new thing, and use "/". I'll leave the decision to you.

**Comment by mmontone** [comment]
I've noticed that there are several filter definitions with &optional arguments, like this:

```
(def-filter :sort (it &optional
		      (predicate #'<)
		      (key #'identity))
```

But I guess those are useless as there's no way of passing those optional arguments.

**Comment by PuercoPop** [comment]
I think I started using / after seeing them in LIL w/o knowing it was part of the ASDF's package inferred extension convention. The dot is used by fukamachi, pjb, hu.dwim, shinmera, etc. The only 'downside' is that Allegro CL provides a reader extension for hierarchical packages.
