### ISSUE TITLE
if condition inside compile token is a contraction

### ISSUE THREAD

**Issue by PuercoPop** [mmontone/djula#24]
Hi

I suspect that [this](https://github.com/mmontone/djula/blob/master/src/compiler.lisp#L144) is supposed to be `(not *fancy-error-template-p*)`

**Comment by mmontone** [comment]
Exactly. Good catch!

**Comment by mmontone** [comment]
https://github.com/mmontone/djula/commit/a184ae7beeb8ee60175c8974cb844cf40116dcfa
