### ISSUE TITLE
Broken Dependency Arnesi

### ISSUE THREAD

**Issue by Disclosure** [mmontone/djula#29]
I have been unable to install Djula using quicklisp on LispWorks on Windows. During installation it throws an error about missing package 'lexical' when compiling Arnesi package.

I had a look into the source, it indeed appears to access the package named lexical, however it does not appear to define in anywhere before hand.

Is that a known problem? The library appears to be almost 10 years old, I would not be holding my breath trying to get help from the author, this is why I am asking here.

**Comment by mmontone** [comment]
On 15/11/15 20:28, Disclosure wrote:
> I have been unable to install Djula using quicklisp on LispWorks on
> Windows. During installation it throws and error about missing package
> 'lexical' when compiling Arnesi package.
> 
> I had a look into the source, it indeed appears to access the package
> named lexical, however it does not appear to define in anywhere before hand.
> 
> Is that an known problem? The library appears to be almost 10 years old,
> I would not be holding my breath trying to get help from the author,
> this is why I am asking here.

I really don't know. Djula doesn't depend directly on arnesi, so one of
the dependencies depends on arnesi (I don't know which one). I didn't
know arnesi didn't compile on LispWorks, I'm not a LispWorks user. I'm
not sure how that can be fixed. Maybe investigating which is the package
that depends on arnesi and maaaybe try to replace it? Djula does not use
arnesi directly anywhere. Can you investigate a bit?

**Comment by PuercoPop** [comment]
The system that depends on arnesi is [cl-locale](https://github.com/fukamachi/cl-locale)

**Comment by mmontone** [comment]
On 16/11/15 00:41, Javier Olaechea wrote:
> The system that depends on arnesi is cl-locale
> <https://github.com/fukamachi/cl-locale>
> 

Ok, thanks. I'm not really sure how to proceed right now. cl-locale
system is one of the backends for Djula translations. The other one is
gettext.

Maybe provide it as a separate compilation feature? Say #+djula-locale,
or something like that. The system would not get included unless
:djula-locale belongs to *features*.

That's just an idea. More ideas are welcomed.

**Comment by mmontone** [comment]
Another option would be to disable cl-locale translation backend for LispWorks (again checking #+lispworks in *features*)

**Comment by mmontone** [comment]
Trying to load Djula on LispWorks, I get another error:

```
CL-USER 6 : 2 > :c 1
Wrote error log to /home/marian/logs/LispWorks/lispworks-personal-6-1-1-x86-linux-log at 2015/11/16 1:06:53

Error: Error while trying to load definition for system
       named-readtables from pathname
       /home/marian/quicklisp/dists/quicklisp/software/named-readtables-20150923-git/named-readtables.asd:

          REINITIALIZE-INSTANCE is called with keyword :MAILTO among the arguments (#<SYSTEM "named-readtables"> :NAME "named-readtables" :PATHNAME #P"/home/marian/quicklisp/dists/quicklisp/software/named-readtables-20150923-git/src/" :PARENT NIL :DESCRIPTION "Library that creates a namespace for named readtable
  akin to the namespace of packages." :AUTHOR "Tobias C. Rittweiler <trittweiler@common-lisp.net>" :MAINTAINER "Gábor Melis" :MAILTO "mega@retes.hu" :VERSION "0.9" :LICENCE "BSD, see LICENSE" :DEFAULT-COMPONENT-CLASS NAMED-READTABLES-SOURCE-FILE) which is not one of (:PROPERTIES :ENCODING :AROUND-COMPILE :PATHNAME :PARENT :DO-FIRST :IN-ORDER-TO :VERSION :NAME :DEFAULT-COMPONENT-CLASS :IF-COMPONENT-DEP-FAILS :COMPONENTS :DEFSYSTEM-DEPENDS-ON :SOURCE-FILE :LICENCE :LICENSE :MAINTAINER :AUTHOR :LONG-DESCRIPTION :DESCRIPTION).
```

Will look at this later this week.

**Comment by Disclosure** [comment]
The above error that you are getting has to do with the dated version of asdf that LispWorks uses. Download the latest asdf package from 

https://common-lisp.net/project/asdf/#downloads

[Direct Link](https://common-lisp.net/project/asdf/asdf.lisp)

Load it using menu File|Load, it will throw a few warnings but that is okay. Afterwards it should be able to start compiling Djula until you hit the error related to Arnesi.

**Comment by mmontone** [comment]
https://github.com/mmontone/djula/commit/3db0e2fb62d9066cd3d279d6d515f036d8198e8b disables cl-locale backend on LispWorks. Djula compiles fine for me, and tests pass.

@Disclosure , give a try, please.

**Comment by Disclosure** [comment]
@mmontone I have just tried it and it compiled as expected, thanks. The issue has been resolved.
