### ISSUE TITLE
Do you have a plan to support Clozure CL?

### ISSUE THREAD

**Issue by fukamachi** [mmontone/djula#3]
I'm wondering if Djula can be used as the default templating engine of [Caveman2](https://github.com/fukamachi/caveman), my web framework.

However, it seems Djula cannot work on Clozure CL.

https://travis-ci.org/fukamachi/djula/jobs/47880575#L644-L648

Do you have a plan to support Clozure CL?

**Comment by mmontone** [comment]
Hi. I haven't tested djula on ccl but I would certainly want to make it work for it. I will have a look as soon as I can. It may take some time as I'm on vacations atm.

**Comment by mmontone** [comment]
I have a fix for it now: https://github.com/mmontone/djula/commit/87c8b9a5e0c1fd77a1262fb5237cbf87ac300884

**Comment by fukamachi** [comment]
Great! It's quite quicker than I expected.
I tested on my fork and it has passed. https://travis-ci.org/fukamachi/djula

You may want [these changes](https://github.com/fukamachi/djula/commit/f20bdc824db525efbe2fe857f1c1feb57408db4c) for testing on Travis CI because cl-travis has switched its backend from cl-launch to [CIM](https://github.com/KeenS/CIM). (Weirdly, it failed for ECL, though. The ECL which cl-travis installs doesn't have thread-support?)

Anyway, I'm closing this. Thanks!
