### ISSUE TITLE
Problem with ifchanged tag

### ISSUE THREAD

**Issue by vladimir-g** [mmontone/djula#31]
I've found strange behaviour of the ifchanged tag. Looks like last value is cached somewhere, so when the loop is rerunned (on second render-template* call, for example), tag doesn't work as intended.

Simple testcase:
```lisp
(defparameter +tpl+ (djula::compile-string "start {% for i in data %}{% ifchanged i %}[changed] {% endifchanged %}{{ i }} {% endfor %}end
"))

(djula:render-template* +tpl+ *standard-output* :data '(1 2)) ; Ok
(djula:render-template* +tpl+ *standard-output* :data '(1 1)) ; Ok
(djula:render-template* +tpl+ *standard-output* :data '(1 1)) ; Wrong
```

Results:
```
start [changed] 1 [changed] 2 end
start [changed] 1 1 end
start 1 1 end
```
That can lead to strange outcome: in real life web application, when loop has one iteration, ifchanged works only when page is opened first time, and doesn't show anything after.

Is it a bug or am I doing something wrong?

**Comment by mmontone** [comment]
This is probably a bug. I don't see why running the same thing several times should return different values in this case. Smells like some mutability issue. Let me look at this in the following days.

**Comment by mmontone** [comment]
I've may have fixed this in https://github.com/mmontone/djula/commit/b25d1ec9442f6c7bbdd8123bbe5dcce64ee4b360

**Comment by vladimir-g** [comment]
Looks like it works now. Thank you.
