### ISSUE TITLE
Any chance to add a notation to call functions in templates?

### ISSUE THREAD

**Issue by fukamachi** [mmontone/djula#34]
Djula allows to access slots of standard-objects, however, apparently it's not possible to call functions/methods inside templates.

For example:

```common-lisp
(defclass person ()
  ((first-name :initarg :first-name
               :accessor person-first-name)
   (last-name :initarg :last-name
              :accessor person-last-name)))

(defgeneric person-full-name (person)
  (:method ((person person))
    (format nil "~A ~A"
            (person-first-name person)
            (person-last-name person))))
```

In this case, `first-name` and `last-name` can be read by `obj.first-name` and `obj.last-name`, but there's no way to do it for `person-full-name`.

Though it can be implemented as a filter, it's not straightforward.

Any ideas?

**Comment by mmontone** [comment]
```{{ person.person-full-name }}``` should work

if not, then that's a bug

**Comment by mmontone** [comment]
This works for me with your example:

```lisp

WEB> (defparameter *template* (djula:compile-string "{{person.person-full-name}}"))
; Evaluation aborted on #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "The symbol ~S is not external in the ~A package." {100717D693}>.
WEB> (defparameter *template* (djula::compile-string "{{person.person-full-name}}"))
*TEMPLATE*
WEB> (djula:render-template* *template* nil :person (make-instance 'person :first-name "Mariano" :last-name "Montone"))
"Mariano Montone"
```

**Comment by mmontone** [comment]
To call functions that need arguments passed, that's another matter :)

**Comment by fukamachi** [comment]
Oh, sorry, I was confused.
It also works for me.
It would be better if it's possible to pass arguments to them, however, it's okay for now.
Thanks!

**Comment by mfiano** [comment]
@mmontone This no longer works - it just results in an empty string.

```lisp
WEB> (defparameter *template* (djula:compile-string "{{person.person-full-name}}"))
; Evaluation aborted on #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "The symbol ~S is not external in the ~A package." {100717D693}>.
WEB> (defparameter *template* (djula::compile-string "{{person.person-full-name}}"))
*TEMPLATE*
WEB> (djula:render-template* *template* nil :person (make-instance 'person :first-name "Mariano" :last-name "Montone"))
"Mariano Montone"
```

**Comment by mmontone** [comment]
This got broken with the latest changes?

**Comment by mfiano** [comment]
I'm not sure about the latest change. I just started using it, and found this to be broken, so I searched the issues and saw your example above that SHOULD work, but all that is returned is a 0-length string.

**Comment by mmontone** [comment]
Ok. Please check that Djula is using the correct package where that function is. 

{% use-package <package >%} or in-package,  I don't remember exactly which  one of those.

**Comment by mmontone** [comment]
But OK, let's keep this issue open and see what can be done about it.

**Comment by mmontone** [comment]
Tests are passing though. Look here: https://github.com/mmontone/djula/blob/master/test/variables.lisp#L106

**Comment by vindarel** [comment]
I am facing this issue too:

```
(djula:render-template* *template* nil :person (make-instance 'person :first-name "Mariano" :last-name "Montone"))
;; => ""
```
instead of "Mariano Montone".

I experience it with another package, and another method.

It turns out that specifying `*djula-execute-package*` makes it working:

```
(defvar *djula-execute-package* (find-package :common-lisp-user)
  "The package in which template expressions are evaluated.")

;; =>

      (let ((djula:*djula-execute-package* :openbookstore.models))
        (djula:render-template* *admin-record* nil
           …
```

but I can't find any `{% use-package … %}` or `{% in-package … %}`.

The "execute-package" thing isn't in the published documentation.

Can we use the current `*package*` instead of `:cl-user`?

--- 

Failing test: add this to the end of test/variables.lisp:

```lisp
(defpackage #:djula-test-second
  (:use #:cl
        #:djula
        #:fiveam))

(in-package #:djula-test-second)

(defclass my-second-obj ()
  ((name :accessor name
	 :initform "my-second-obj")))

(defmethod id ((obj my-second-obj))
  (declare (ignore obj))
  44)

(def-test variables-accessing-test (:compile-at :definition-time)
  (let ((djula:*catch-template-errors-p* nil))

    ;; Method accessing and *djula-execute-package*
    (is (equalp
	 (let ((djula:*djula-execute-package* :djula-test))
	   (let ((template (djula::compile-string "{{obj.id}}")))
	     (djula:render-template* template nil :obj (make-instance 'my-second-obj))))
	 44))

    ))
```
=>
```
(setf fiveam:*run-test-when-defined* t)

; compiling (DEF-TEST VARIABLES-ACCESSING-TEST ...)
Running test VARIABLES-ACCESSING-TEST f
 Did 1 check.
    Pass: 0 ( 0%)
    Skip: 0 ( 0%)
    Fail: 1 (100%)

 Failure Details:
 --------------------------------
 VARIABLES-ACCESSING-TEST []: 
      
44

 evaluated to 

44

 which is not 

EQUALP

 to 

""
```

**Comment by mmontone** [comment]
There's the [set-package](https://github.com/mmontone/djula/blob/9394c397348a1aea5ddde49919332e127a6c69fa/src/tags.lisp#L255) tag.

Try with it, please. If it works, then we should document. (Also: should we rename it to `in-package` so as to be more consistent with CL idioms?). If it doesn't, I'll have a deeper look. I think it did not always work, or something like that, for some reason.

**Comment by mmontone** [comment]
A thing I think is also worth looking at: the `set-package` tag uses `setf` to set the execute package. But then that means that a `set-package` in template A could affect the execute package in template B, unless the execute package is resetted upon each rendering, that I guess it is not.

**Comment by mmontone** [comment]
Let's move this to a separate issue #92
