### ISSUE TITLE
comparison in if blocks

### ISSUE THREAD

**Issue by mtstickney** [mmontone/djula#4]
Comparison expressions (using == or !=) in if blocks currently don't work, because the parser isn't looking for them. It will pick up 'and' and 'or', but == and != just get parsed as variables. Parentheses are also broken in that context (it parses a list of items and attempts to coerce it to a string).

An expression parser would be pretty simple to do, given the limited number of operators, but I won't have time to work on it for a bit and thought you might like to know about the issues anyway.

**Comment by mmontone** [comment]
Thanks for reporting. Yes, the logical statements compilation is very weak. I will try to implement a better parser when I have time.

**Comment by mmontone** [comment]
I've implemented a parser. Please pull from master and test.

**Comment by mtstickney** [comment]
Seems to be working correctly, parens and all. Thanks for the quick turnaround.
