### ISSUE TITLE
How to access elements of a plist

### ISSUE THREAD

**Issue by fungiblecog** [mmontone/djula#40]
Sorry if this is obvious, but I've read the docs and although there is a reference to accessing elements of an alist I don't see anything for plists (or lists in general) other than looping over the elements. I want to access arbitrary key value pairs by key.

**Comment by mmontone** [comment]
Hello. Djula uses cl-access library for accessing things. 

So the `plist.key` syntax should work.

Let me know if it doesn't.

**Comment by fungiblecog** [comment]
Sweet, that works perfectly.

**Comment by abishek** [comment]
Can someone give an example of this type of looping? I am a noobie tryna get this working..

**Comment by abishek** [comment]
> Can someone give an example of this type of looping? I am a noobie tryna get this working..

Thanks! I got it working. I was making a mistake in the way I was writing my code.
