### ISSUE TITLE
regexp filter

### ISSUE THREAD

**Issue by knobo** [mmontone/djula#43]
Any reason we don't have filters like this:

``` cl
(def-filter :replace (it regex)
  (lambda (replace)
    (cl-ppcre:regex-replace-all regex it replace)))

(def-filter :with (it replace)
  (funcall it replace))

(def-filter :scan (it regex)
  (cl-ppcre:scan-to-strings regex it))

;; Use like this:   {{ data  | replace:1| with:2}}
```

**Comment by mmontone** [comment]
How would you use the :scan filter? Do you have an example?

**Comment by knobo** [comment]
The scan filter uses scan-to-strings. 
So let's say I', looking for the month in the date 2018-04-11, I could do
`(cl-ppcre:scan-to-strings "(?<=-)[0-9]*" "2018-04-11")`

Then I'd do something like `{{ date | scan:"(?<=-)[0-9]*" }}` in the template.

If I'm looking for the first 3 letter word in a string, I could do something like this:

``` cl
(djula:render-template* "test.html" nil 
                        :foo "RE: FV: RE: Survey: Do you have the time?")
```
   
Template:
` {{ subject | scan:"[a-zA-Z]{3,}:" }}`
