### ISSUE TITLE
How to build the Sphinx documentation?

### ISSUE THREAD

**Issue by vindarel** [mmontone/djula#51]
Hi, I tried to build the Sphinx documentation with these packages:

        pip2 install --user sphinx sphinx_bootstrap_theme sphinxcontrib.cldomain

but with `make html`:

> Could not import extension sphinxcontrib.cldomain (exception: cannot import name Directive)

Did I fetch the right packages? What's in your local installation?

**Comment by mmontone** [comment]
I'm installing with with pip install clphinxcontrib-cldomain, and the extension is found.

Have an cl-launch error now. I'll update my progress here. I haven't build the docs for a long time.

**Comment by mmontone** [comment]
@vindarel 

I've added a README to the docs folder with some instructions to build the doc.

Let me know if they work for you. Had to fork sphinxcontrib-cldomain and fix it for python3, etc.

**Comment by vindarel** [comment]
Works fine, thanks.
