### ISSUE TITLE
Is it possible to compile/render a template placed anywhere on the disk?

### ISSUE THREAD

**Issue by iamFIREcracker** [mmontone/djula#63]
I am working on a small _convert_-like utility that, given a djula template (specified as command line option), would:

- Read some text from the standard input
- Transform it
- Call RENDER-TEMPLATE* to generate the _converted_ output

The problem that I am currently facing is, how to compile/render the template without having to call ADD-TEMPLATE-DIRECTORY first. 

Is it actually possible to do so? Any hint of where should I look to get this implemented?

Thanks in advance.

**Comment by mmontone** [comment]
If you have a file:

```lisp
(djula:render-template* (pathname "my-template.html"))
```

You can also compile/render strings:

```
(djula:render-template* (djula::compile-string (alexandria:read-file-into-string "/home/marian/src/lisp/djula/test/templates/t1.djula")))
```

Is that useful?

**Comment by iamFIREcracker** [comment]
```
(djula:render-template* (pathname "my-template.html"))
```

I thought TEMPLATE, the first argument, had to be the return value of COMPLETE-TEMPLATE*, but I guess I was wrong.  Awesome, this definitely solves my problem.

Thanks a lot!
