### ISSUE TITLE
Using ifequal (or similar tag) with a filtered value

### ISSUE THREAD

**Issue by Stephane-T** [mmontone/djula#68]
Hello,

Case is simple, I have a list of list (returned by a SQL request using postmodern) who looks like this

(let ((customers (send-sql "select id, name from customers where account = $1 order by name" account))

It returns something such as 

((1,"toto")(2,"titi")(3,"tutu"))

I can use this list inside a select to select a customer :+1: 

	          <select class="form-control" id="accounts" name="account">
		        {% for line in customers %}
		        <option value="{{ line|first }}">{{ line|slice:1|first }}</option>
		        {% endfor %}
	          </select>

I would like to pre-select the current selected entry with a code who should look like 

{% ifequal line|first customer %}
selected
{% endifequal %}

Maybe I missed something in the doc, but would it not be possible to get a tag to return an entry from the list (such as slice in the filters).

**Comment by Stephane-T** [comment]
I answer to myself, I can use line.0 to get the first entry of the list.

**Comment by mmontone** [comment]
So, is this solved? Close the issue?

**Comment by Stephane-T** [comment]
You may want to update the documentation because it's really an important feature to be able to address an entry in a list. Beside that, yes, can close (I do it).
