### ISSUE TITLE
Proposal to iterate a fixed number of times with `for` (à la dotimes)

### ISSUE THREAD

**Issue by vindarel** [mmontone/djula#69]
Hi,

I'd like to iterate a fixed number of times. The for tag doesn't accept an integer, there is no dotimes.

But maybe adding this clause to create an iterable out of the integer:

```lisp
;; 
(defun iterable-list (iterable)
  (typecase iterable
    (array (coerce iterable 'list))
    (hash-table (alexandria:hash-table-alist iterable))
    (sequence iterable)
    (integer (make-list iterable))  ;; <---------- added
    (t (error "Cannot iterate on ~A" iterable))))
```

I just borked my environment so I'll try later, so if you have better ideas I'm all ears.

Best,

**Comment by mmontone** [comment]
I'm not against. But, I'm thinking ... what if we make iterable-list a generic function, so that the user can adapt to his own data structures if needed?

```lisp
(defmethod iterable-list ((n integer))
    (make-list n))
```

**Comment by mmontone** [comment]
> > Also, not pretty, but doesn't something like `{% for x in n.make-list %}` work?
> 
> This is incorrect as `make-list` returns a list with NILs. But it is possible to use a range function for example: https://quickref.common-lisp.net/serapeum.html#go-to-the-SERAPEUM_2236_2236RANGE-function.

I mean, make-list works, but you cannot access the index in `x` if you need them.
