### ISSUE TITLE
Can't render a string variable

### ISSUE THREAD

**Issue by anthonyshull** [mmontone/djula#8]
(defroute "/" ()
  (let ((token (cdr (split-sequence:split-sequence #\| (drakma:http-request *url*)))))
    (render #P"index.html" '(:token token))))

I need to be able to render a string represented by a variable. Using {{ token }} just renders TOKEN instead of rendering the actual value of the variable 'token.'

How do I pass a string variable to the template?

**Comment by mmontone** [comment]
You have to use render-template*

(defun render-template* (template &optional stream &rest *template-arguments*)

Notice that you have to pass a stream (or NIL) before the arguments, and the arguments are a property list.

In your case, something like:

(defparameter +index.html+ (djula:compile-template* #p"index.html"))

and then:

(with-output-to-string (s)
        (djula:render-template* +index.html+ s :token token))

Also, you can look at the demo: (require :djula-demo) (djula-demo:start-demo)

**Comment by anthonyshull** [comment]
I should have been more clear that I'm using Caveman2. I wasn't passing the last param as plist.

So, I needed (list :token token) instead of '(:token token) which is a string. I'm new to Lisp :)
