### ISSUE TITLE
(minor) doc additions on i18n

### ISSUE THREAD

**Issue by vindarel** [mmontone/djula#86]
Hi Mariano,

A quick message: when I read https://mmontone.github.io/djula/djula/Internationalization.html#Backends

- it is missing the reference to Shirakumo's  Translate
- it should mention early on that we must load the related system, such as "djula-gettext". BTW I was hit by an error because of this change, it could be helpful to have a changelog (new file or in the readme) to inform of the latest breaking changes?

Best,
(no PR today)

**Comment by mmontone** [comment]
Hi Vincent,

Ok. I'll add documentation for Shirakumo's translate backend, and add a note that loading the translation backend ASDF system is required.

Thanks.

**Comment by mmontone** [comment]
> * BTW I was hit by an error because of this change

I'm not aware of an api breaking change. If there is, it was not intended.

**Comment by mmontone** [comment]
There could a problem with the type declarations. I'll check. On the other hand, translation are not supposed to work with no backend loaded, so I don't know .. I think I could make them work with no backend loaded, make translate just return the given string without translating.

**Comment by vindarel** [comment]
that is an idea, but the addition of the error message that you committed is actually very helpful and all I needed.

IIRC a function type declaration was strict on requiring an asdf-package-name and not accepting a string, but I had two issues at once so I can't tell right now.

**Comment by mmontone** [comment]
> IIRC a function type declaration was strict on requiring an asdf-package-name and not accepting a string, but I had two issues at once so I can't tell right now.

What was the function, you know? Perhaps I should consider removing the type declarations. I was experimenting a bit with types in Lisp so that the user gets fast feedback when trying to pass an argument with incorrect type. But the declared type need to be correct.

**Comment by mmontone** [comment]
It is probably this: (ftype (function (symbol asdf:component) list) list-asdf-system-templates))

**Comment by vindarel** [comment]
so I had an issue with `djula:list-asdf-system-templates` not wanting a string anymore. IDK if it's only one nor if it's simple to fix.

**Comment by mmontone** [comment]
I've adjusted the type, but it is bothersome, I'll just remove the type declarations.

**Comment by vindarel** [comment]
ok. I'll try and confirm.

**Comment by mmontone** [comment]
But that needs to be an ASDF component. (asdf:component-children sys) is used inside ..

**Comment by mmontone** [comment]
Ok, I'll remove the type of that function. It seems it can accept more things than I supposed.

**Comment by vindarel** [comment]
this initial version at least works :) 

```
CL-USER> (djula::list-asdf-system-templates "bookshops" "src/web/templates")
(#P"/home/vince/projets/openbookstore/openbookstore/src/web/templates/login.html"
 #P"/home/vince/projets/openbookstore/openbookstore/src/web/templates/404.html"
…)

(defun list-asdf-system-templates (asdf-system component)
  "List djula templates in ASDF-SYSTEM at COMPONENT.
A list of template PATHNAMEs is returned."

  (let* ((sys (asdf:find-system asdf-system))  ; <---- FIND THE SYSTEM FROM STRING
         (children (asdf:component-children sys))
         (module (or (find component children :key #'asdf:component-name :test #'equal) ;; <- FIND THE COMPONENT FROM STRING TOO
                     (error "Component ~S not found in system named ~S.~&Available components are: ~S" component asdf-system (mapcar #'asdf:component-name children))))
         (alltemplates (remove-if-not (lambda (x) (typep x 'asdf:static-file))
                                      (asdf:module-components module))))
    (mapcar (lambda (it) (asdf:component-pathname it))
            alltemplates)))
```

: - )

**Comment by mmontone** [comment]
Yes, it was an oversight by me. I've just removed the type declaration. Everything ok now?

**Comment by vindarel** [comment]
I'm back on djula:master and EVERYTHING's OK, THANK YOU <3
