### ISSUE TITLE
cannot use base.html and subdir/base.html in inheritance chain

### ISSUE THREAD

**Issue by krsanky** [mmontone/djula#89]
Hi!,
Djula is great!

I am a django template user from way back.

I have just debugged a weird case with a common inheritance pattern.

I have the bottom "base.html".

In a subdirectory I want to extend it with common features to some module.

So I have "search/base.html" extends "base.html".
And then everything in search/ will extend the local search/base.html.
Pretty typical pattern, i almost make it more confusing explaining it.

Ok with that above pattern I get:
fatal error encountered in SBCL pid 55444 pthread 0x1ac6c06fc30:
Control stack exhausted while pseudo-atomic, fault: 0x1ac40d17fa0, PC: 0x1ac6c066f86

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>

If I change search/base.html to search/base_search.html (or whatever) it works.

So something with the common base name is causing some loop ? obviously i have no idea :)

Anyways the workaround works but i did narrow it down enough to repro in case this interests you.

Thanks!!!!
Paul SomeoneElse

**Comment by krsanky** [comment]
Darnit, now it seems just intermittent.  I can't consistently get a 2 level inheritance setup working.

**Comment by mmontone** [comment]
Thanks for reporting. I'll take a look.

**Comment by mmontone** [comment]
Yes. Problem is current store doesn't look at file system directories as part of template names, behaves kind of a global database of template filenames, regardless of subdirectories. And so extends "base.html" in `search` directory enters an infinite loop. I don't have a quick fix for that for now. I'd need to rethink how the store manages filenames + directories.

**Comment by mmontone** [comment]
I've pushed a change you can try. It is not a fix, only changes the priority when looking for templates in file system. But could help with this.

**Comment by mmontone** [comment]
I'm going to try to implement relative includes now. I think they could be a simple to implement solution to this.

**Comment by mmontone** [comment]
I've implemented relative extends, so you can point directly to your templates using "../base.html" in `extends`in subdirectories. Does it help?

**Comment by krsanky** [comment]
Thanks for looking at this!
I've started work today after being on vacation so I'm super busy :)
I'll be looking into this in the next day or so.

**Comment by krsanky** [comment]
I found when I implement a template cache that it is easier to just include the full path as the key instead of just the base name.  I think this also logically makes sense because base.html is completely a different thing than subdir/base.html.  And that's the Django idiom.

But I haven't looked at what you've done so, take that with a grain of salt until I do.

Thanks again!

**Comment by mmontone** [comment]
Ok. I'll take a look at the cache too.

**Comment by krsanky** [comment]
; compiling file "/disk1/home/wise/quicklisp/local-projects/djula/src/template-store.lisp" (written 02 JAN 2024 03:40:0
7 PM):                                                                                                                 
;                                                          
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package PATH does not exist.
;   
;       Line: 37, Column: 41, File-Position: 1289
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /disk1/home/wise/quicklisp/local-projects/djula/src/template-st
ore.lisp" {1003A25873}>

; compilation aborted after 0:00:00.001

**Comment by krsanky** [comment]
I got that putting a checkout of the latest djula repo into my ~/quicklisp/local-projects/  directory.
Caveat, this is only the second time I've tried this quicklisp/common-lisp feature so I could be doing it wrong.

**Comment by mmontone** [comment]
There was a problem with dependencies. Can you try again? Apologies.

**Comment by krsanky** [comment]
Thanks!,

This is worse.  

For this example my sub-app is "todo":

Previous this works:
base.html
todo/base_todo.html <-- this extends base.html with {% extends "todo/base_todo.html" %}

Now that doesn't work:


debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10013A00A3}>:
  No current path for relative pathname: "todo/index.html"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

((:METHOD DJULA:FIND-TEMPLATE (DJULA:FILESYSTEM-TEMPLATE-STORE T)) #<DJULA:FILESYSTEM-TEMPLATE-STORE {1005D195A3}> "todo/index.html" T) [fast-method]
   source: (ERROR "No current path for relative pathname: ~s" NAME)
0] 



Did you make sub-directory paths not work at all?

I think it's more idiomatic to django (and jinja) to be able to organize with directories even if you can't reuse the base.html filename.

**Comment by mmontone** [comment]
Ok. I'll revert or come up with a solution.

**Comment by mmontone** [comment]
> Thanks!,
> 
> This is worse.
> 
> For this example my sub-app is "todo":
> 
> Previous this works: base.html todo/base_todo.html <-- this extends base.html with {% extends "todo/base_todo.html" %}
> 
> Now that doesn't work

This should work again. But I need to take time to test it.

**Comment by mmontone** [comment]
I've added some tests. Seems to be in good shape to me now.
