### ISSUE TITLE
Test broken on ECL `(ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :DJULA "test/templates/t1.djula")`

### ISSUE THREAD

**Issue by hraban** [mmontone/djula#90]
Running `(asdf:test-system "djula")` with `ECL 23.9.9` on an ARM Mac I get:

```
Running test suite DJULA-TEST
 Running test COMPILER .
 Running test CATCH-ERRORS-TEST ....
 Running test FILTERS ...........................
 Running test APPLY-FILTERS .
 Running test REGEX-FILTERS ...
 Running test LEXER ...
 Running test PARSER .
 Running test FIRSTOF ......
 Running test CYCLE .
 Running test JS ..
 Running test LANGUAGE ..
 Running test LOGIC ..
 Running test CONDITIONAL-TEST ..........................
 Running test ELIF-TEST ...
 Running test LOOP-TEST ................
 Running test NESTED-LOOP-TEST .
 Running test LOGICAL-STATEMENTS-TEST ...........
 Running test LISP-TAG-TEST ...
 Running test COMMENT-TEST ..
 Running test IFEQUAL-TEST .......
 Running test IFNOTEQUAL-TEST ...
 Running test VERBATIM-TEST ..
 Running test AUTOESCAPE-TEST ...........
 Running test IFCHANGED-TEST ...
 Running test VARIABLES-TEST ....
 Running test APPLY-KEYS/INDEXES-TEST .
 Running test VARIABLES-ACCESSING-TEST .............
 Running test ESCAPING-TEST ......
 Running test DEFAULT-TEMPLATE-ARGUMENTS ....
 Running test SIMPLE-BLOCK-TEST .
 Running test ONE-LEVEL-BLOCK-INHERITANCE-TEST .
 Running test TWO-LEVELS-BLOCK-INHERITANCE-TEST .
 Running test EXTENDS-ERROR-TEST .
 Running test SIMPLE-SUPER-TEST .
 Running test SIMPLE-ANNON-SUPER-TEST .
 Running test SUPER-ERROR ..
 Running test INCLUDE-TEST .
 Running test INCLUDE-WITH-VARS-TEST .
 Running test MULTIPLE-LEVELS-BLOCK-INHERITANCE-TEST .
 Running test PARAMETERIZED-INCLUDE-TEST .
 Running test PARAMETERIZED-INCLUDE-WITH-VARS-TEST .
 Running test RELATIVE-EXTENDS-1-TEST .
 Running test RELATIVE-EXTENDS-2-TEST .
 Running test RELATIVE-EXTENDS-3-TEST .
 Running test RELATIVE-EXTENDS-4-TEST .
 Running test FIND-TEMPLATE-TEST An error occurred during initialization:
The following check failed: (EQUALP (FIND-TEMPLATE* "t1.djula" NIL)
                                    (ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME
                                     :DJULA
                                     "test/templates/t1.djula"))

(ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :DJULA "test/templates/t1.djula")

 evaluated to

#P"/Users/user/code/common-lisp/djula/test/templates/t1.djula"

 which is not

EQUALP

 to

#P"/Users/user/code/common-lisp/djula/test/templates/t1.djula"

..
```

(pretty weird error message tbh 🤔)

Works fine on SBCL.

**Comment by mmontone** [comment]
Hi. Yes. I've seen it. I think there's something wrong with pathname comparisons in some implementations.
Thanks for reporting. I'll leave this open til I find a fix.

**Comment by mmontone** [comment]
I think it is just the test that breaks, the implementation is correct.

```
(ASDF/SYSTEM:SYSTEM-RELATIVE-PATHNAME :DJULA "test/templates/t1.djula")

 evaluated to

#P"/Users/user/code/common-lisp/djula/test/templates/t1.djula"

 which is not

EQUALP

 to

#P"/Users/user/code/common-lisp/djula/test/templates/t1.djula"
```

That should be true, but the `equalp` returns `nil` for some reason.

**Comment by hraban** [comment]
from ECL:

```
> (pathname-version (djula:find-template* "t1.djula"))

:NEWEST
> (pathname-version (asdf:system-relative-pathname :djula "test/templates/t1.djula"))

NIL
```
That would explain it

**Comment by mmontone** [comment]
Oh. Thanks. I didn't know about pathname-version. And how it is relevant to equality. Do you have a suggestion for a fix?

**Comment by mmontone** [comment]
Perhaps I could use a custom `pathname-equalp` function in the tests, that uses `string=` and `princ-to-string` of the pathnames. But there may be better.

**Comment by hraban** [comment]
I wonder why the path returned by djula has its version set to `:newest` in the first place, though.. it might cause other issues downstream users who will (understandably) expect the same behaviour from pathnames as you originally did when writing this test. It's a fair test, and if you ask me it caught a pretty tricky bug.

Maybe it's worth `djula:find-template*` ensuring that the version is `NIL`, instead?

**Comment by mmontone** [comment]
Problem is here: https://gitlab.com/embeddable-common-lisp/ecl/-/blob/develop/src/c/pathname.d?ref_type=heads#L711

ECL assigns `:newest` to paths with a name and a type when parsing.

**Comment by hraban** [comment]
🙄  dzjeebus.

Ok that's life then. Yuck. Why would they do that.

So you were right after all, this means the pathname version might as well be totally ignored?

**Comment by mmontone** [comment]
Actually I was wrong. That's not the issue. SBCL does the same. I don't
know where the difference is. I've tried changing the implementation in
some ways but didn't make a difference. Whatever it is, it is very subtle.

**Comment by mmontone** [comment]
@hraban I've pushed a fix. It is not clean. But I don't know how to do better at this moment.

**Comment by hraban** [comment]
> Actually I was wrong. That's not the issue. SBCL does the same. I don't know where the difference is. I've tried changing the implementation in some ways but didn't make a difference. Whatever it is, it is very subtle. 

TIL -- I had no idea.

I think it's a fine fix 🤷‍♀️
