### ISSUE TITLE
Template execution package

### ISSUE THREAD

**Issue by mmontone** [mmontone/djula#92]
Review execute package behaviour, docs, etc.

See: https://github.com/mmontone/djula/issues/34#issuecomment-1969409675

**Comment by mmontone** [comment]
@vindarel I've done some work in a separate branch here: https://github.com/mmontone/djula/tree/template-execute-package

I've renamed `*djula-execute-package*` to `*template-package*` and added a section about the template package in `Templates` section in docs. (you should be able to build the docs running `make` in the `docs` directory).

What do you think of it?

**Comment by vindarel** [comment]
I didn't test it yet, but the explanation is clear. It could be even more useful to mention that the need arises when trying to evaluate `{{ object.method }}` where "method" is a generic function (because accessing slots works fine).

**Comment by vindarel** [comment]
but using `(let ((djula:*djula-execute-package)) … (render-template*))` would not be global? (if not it can be added to the doc)

**Comment by mmontone** [comment]
Ok. Those are good points. I'll update the docs.
