### ISSUE TITLE
Variable named "format"

### ISSUE THREAD

**Issue by john-floren-gravwell** [mmontone/djula#93]
I think I'm hitting an interesting corner case with the naming of an object slot. I'm building a site with caveman2, which uses djula for formatting. I pass a list of radio stations in and iterate over them in my template... but one of the slots I'm trying to print is named "format":

```
    {% for station in stations %}
    <li> <a href="/station/{{ station.callsign }}">{{ station.callsign }} {{ station.city }} {{ station.format }}</a>
    {% endfor %}
```

When I visit the page, I see this:

```
KDSK Albuquerque There was an error while accessing the attribute :FORMAT of the object #: invalid number of arguments: 1
```

Any other slot (power, latitude, longitude, etc.) that's defined on my object can be output just fine

I fear that the name "format" is colliding with the filter named "format", and would appreciate any suggestions ("rename the slot" isn't great but it is an option)

**Comment by mmontone** [comment]
Does your object have an accessor function for the `format` slot, that is not called `format`? One option is to use the accessor name.

**Comment by mmontone** [comment]
Anyway, I'm looking at this as I'm not sure your code should signal an error...

**Comment by mmontone** [comment]
Yes, the problem is with `access` library that Djula uses for accessing objects. It is calling the `format` function, not accessing the slot ...

**Comment by john-floren-gravwell** [comment]
I'm using mito's deftable macro, which automatically defines accessors like station-format, but if I try `{{ station.station-format }}` I get nothing at all in my template (I've verified that I can call the station-format accessor function from the REPL within my web package)

**Comment by john-floren-gravwell** [comment]
I tried adding a `(let (djula*template-package* :my-package-name)` to my render function, but compilation returns the error `Symbol "*TEMPLATE-PACKAGE*" not found in the DJULA package.`

**Comment by mmontone** [comment]
I think Quivklisp version is outdated. Either clone new version or look for
*djula-execute-package* instead. The rename is fairly recent and Quicklisp
has not been updated for a long time now.

**Comment by john-floren-gravwell** [comment]
That works! Thank you!
