### ISSUE TITLE
Symbol *template-package* does not exist

### ISSUE THREAD

**Issue by 3inven** [mmontone/djula#94]
Djula documentation section 9.1 mentions binding `*template-package*` to cause template evaluation in a desired package, but the symbol `djula:*template-package*` does not seem to exist.  What could I be missing?

**Comment by mmontone** [comment]
I think you are using Quicklisp version of Djula, that is outdated.

**Comment by mmontone** [comment]
For old versions you can use `*djula-execute-package*` if I remember correctly.

**Comment by 3inven** [comment]
Yes.  Installed new djula version from ultralisp and there it is, `djula:*template-package*.`
Many thanks for the quick help.
