### ISSUE TITLE
ifchanged doesn't support else tag

### ISSUE THREAD

**Issue by nytpu** [mmontone/djula#98]
The documentation mentions that the `ifchanged` tag supports an `else` tag, like `if` and `ifequals`: http://mmontone.github.io/djula/djula/Tags.html#ifchanged-1

However, when compiling the example from the documentation:
```
{% for match in matches %}
    <div style="background-color:
        {% ifchanged match.ballot-id %}
            {% cycle "red" "blue" %}
        {% else %}
            gray
        {% endifchanged %}
    ">{{ match }}</div>
{% endfor %}
```
Or a more minimal example:
```
{% for object in objects %}{% ifchanged object %}changed!{% else %}not changed.{% endifchanged %}{% endfor %}
```
In both cases, when compiling Djula produces the error:
```
  {# Error: Tag compiler not found: ELSE - compiling the token (TAG ELSE) #}
; ...
(DJULA::COMPILE-TOKEN (:PARSED-FOR (:OBJECT :IN :OBJECTS) (:PARSED-IFCHANGED (:OBJECT) (:STRING "changed!") (:TAG :ELSE) (:STRING "not changed."))))
   source: (ERROR E1)
```

**Comment by mmontone** [comment]
I've implemented support for `else`, but I'm not sure how it should work.
Is this correct behavior:?

```
CL-USER> (djula:render-template* (djula:compile-string "{% for object in objects %}{% ifchanged object %}changed!{% else %}not changed!{% endifchanged %}{% endfor %}") nil :objects '(a a a b c))
"changed!not changed!not changed!changed!changed!"
```

**Comment by nytpu** [comment]
I get the same error when I try to run that snippet:
![Screenshot_20241214_110229](https://github.com/user-attachments/assets/4e84a1f5-a8d3-493a-8262-853255c47584)

I guess I should've said that I was using SBCL and the version from Quicklisp dist 2024-10-12.  But I also get it after loading the latest git commit (`646ae90`) as well, that's what the above screenshot is from.

**Comment by mmontone** [comment]
I hadnt' pushed because I don't know if the semantics are correct. But I've pushed now so that you can test it.

**Comment by nytpu** [comment]
Oh yeah, those semantics are what I would expect.  And it works now after pulling the new version.  Thanks!
