### ISSUE TITLE
How to use emojis?

### ISSUE THREAD

**Issue by dertuxmalwieder** [mmontone/djula#99]
Perhaps I misunderstood something, but I wonder why this

<img width="477" alt="Bildschirmfoto 2024-12-13 um 01 05 58" src="https://github.com/user-attachments/assets/4f919d13-d8d6-457c-895a-639bbdc5e895" />

is rendered like this

<img width="125" alt="Bildschirmfoto 2024-12-13 um 01 07 24" src="https://github.com/user-attachments/assets/0fc8df8f-d522-4a9f-9a14-b24603bcba01" />

when being loaded from Djula. The template file is UTF-8-encoded, so that should not be a problem.

**Comment by mmontone** [comment]
I don't know. I'm getting the emojis rendered:

![image](https://github.com/user-attachments/assets/132656c1-4566-4562-a531-68934e04d805)

Maybe try with a more common emoji?

**Comment by dertuxmalwieder** [comment]
Hmm. Fascinating: It works on the CLI.

![Unbenannt](https://github.com/user-attachments/assets/41b2f300-3194-40fa-87be-a0ee39c568f3)

Something must be lost over the web browser. 🤨

**Comment by mmontone** [comment]
Are you setting [HTML encoding header](https://www.w3.org/International/questions/qa-html-encoding-declarations) ?

**Comment by dertuxmalwieder** [comment]
🤦‍♂️

Fixed.
